name: Colorblind Snapshot Analyzer
description: Analyzes screenshots in PRs for colorblind accessibility using simulated vision filters.
author: NotTheRealWallyx

inputs:
  repo-token:
    description: GitHub token to post comments and access PR files
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install pdm
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Convert pyproject.toml from Poetry to PDM
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        echo "Poetry version:"
        poetry --version
        echo "Repo contents:"
        ls -la
        if [ -f "pyproject.toml" ]; then
          PDM_IGNORE_VENV=1 pdm import -vf poetry pyproject.toml
        else
          echo "❌ pyproject.toml not found in the checked-out repo"
          exit 1
        fi

    - name: Install dependencies from pyproject.toml using pdm
      shell: bash
      run: |
        PDM_IGNORE_VENV=1 pdm install

    - name: Run Colorblind Snapshot Analyzer
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        PR_NUMBER: ${{ env.PR_NUMBER }}
      run: |
        python ${{ github.action_path }}/colorblind_snapshot_analyzer/main.py "${{ inputs.path }}"

branding:
  icon: "eye"
  color: "blue"
