name: Bug Report
description: Report a bug in the LinkSentinel project.
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following details to help us resolve the issue.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Provide a brief summary of the bug.
      placeholder: "e.g., The CLI crashes when running 'python -m linksentinel ./docs'."

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the issue.
      placeholder: |
        1. Run `python -m linksentinel ./docs`.
        2. Observe the error.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "e.g., The CLI should list all tags without crashing."

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "e.g., The CLI crashes with a traceback."

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment (OS, Python version, etc.).
      placeholder: "e.g., macOS 13.0, Python 3.9"
