name: Test Colorblind Snapshot Analyzer

on:
  pull_request:
    branches:
      - never-trigger-this-branch
    types: [opened, synchronize, reopened]

jobs:
  test-colorblind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Colorblind Snapshot Analyzer
        uses: NotTheRealWallyx/colorblind-snapshot-analyzer@1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
