name: Test Colorblind Snapshot Analyzer Locally

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  test-colorblind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Colorblind Snapshot Analyzer script
        run: npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
